---
title: "Tutorial"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Tutorial}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
is_ghactions <- identical(Sys.getenv("CI"), "true")

```

According to [ModelMuse documentation](
https://water.usgs.gov/nrp/gwsoftware/ModelMuse/Help/index.html?head_and_drawdown_panes.htm)
`heads` and `drawdowns` will be saved with the following `file extensions`: 

* **heads**: `.fhd` if it is a formatted text file and `.bhd` if it is a binary file. 

* **drawdowns**: `.fdn` if it is a formatted text file and `.bdn` if it is a binary file.

```{r define_paths}
#remotes::install_github("kwb-r/dwc.ar4gw", dependencies = TRUE)
library(dwc.ar4gw)

### Download model files from KWB cloud:
### 1. Run: usethis::edit_r_environ()
### 2. Add required environment variables
### NEXTCLOUD_URL = "https://url-of-nextcloud.com"
### NEXTCLOUD_USER = "username"
### NEXTCLOUD_PASSWORD = "nextcloud-app-password" 
### for creating "nextcloud-app-password": 
### a) go to: https://url-of-nextcloud.com/index.php/settings/user/security
### b) create new app password
### Finally restart Rstudio

### define paths
paths_list <- list(
  tdir = tempdir(), 
  cloud_dir = "dwc/Work-Packages/WP3_Public_Involvement/AR4GW/ModelData/MF2005",
  local_dir = "C:/kwb/projects/<cloud_dir>",
  download_dir = tempdir(),
  modflow_dir = "<root_data>",
  model_name = "MB16",
  mfout = "<modflow_dir>/<model_name>",
  mf_nam = "<mfout>.nam",
  mf_bas = "<mfout>.bas",
  mf_dis = "<mfout>.dis",
  text_heads = "<mfout>.fhd",
  text_drawdown = "<mfout>.fdn",
  binary_cell.by.cell = "<mfout>.cbc",
  binary_heads = "<mfout>.bhd",
  binary_drawdown = "<mfout>.bdn"
)

paths <- kwb.utils::resolve(paths_list, root_data = paths_list$download_dir)
#paths <- kwb.utils::resolve(paths_list, root_data = paths_list$local_dir)
```


```{r nextcloud_download}

# Download .cbc and .bhd files
mf_files <- kwb.nextcloud::list_files(
  paths$cloud_dir,
  full_info = TRUE) %>%
  dplyr::filter(stringr::str_detect(.data$file,
                                    pattern = sprintf("^%s\\.",  
                                                      paths$model_name))) %>% 
  dplyr::filter(stringr::str_detect(.data$file,
                                    pattern = "cbc$|bhd$|dis$"))

mf_files

kwb.nextcloud::download_files(href = mf_files$href,
                              target_dir = paths$download_dir)

```


## Install flopy

```{r install_flopy, eval = is_ghactions}
reticulate::install_miniconda()

### create an environment "flopy" for installing "flopy" 

reticulate::conda_create(envname = "flopy", packages = "flopy")
```

## Use flopy 

```{r use_flopy, eval = TRUE}

reticulate::use_miniconda(condaenv = "flopy", required = TRUE)

pyconfig <- reticulate::py_config()
pyconfig

reticulate::use_python(python = pyconfig$python, required = TRUE)

## on windows: (try this: https://github.com/rstudio/reticulate/issues/367#issuecomment-432920802)
if(.Platform$OS.type == "windows") {
  Sys.setenv(PATH= paste(PATH = pyconfig$pythonpath,
                         Sys.getenv()["PATH"], sep=";")
  )

}

# reticulate::py_help(object = flopy$utils$postprocessing$get_extended_budget)
extended_budget <- dwc.ar4gw::get_extended_budget(cbcfile = paths$binary_cell.by.cell) 

str(extended_budget)

flopy <- dwc.ar4gw::import_flopy()

# reticulate::py_help(object = flopy$utils$binaryfile$HeadFile)
heads <- flopy$utils$binaryfile$HeadFile(filename = paths$binary_heads,
                                         verbose = TRUE)

# reticulate::py_help(object = heads$get_times)
times <- heads$get_times()[[1L]]

dat_heads <- stats::setNames(
  lapply(times, function(time) {
  heads$get_data(totim = time) }),
  nm = sprintf("time_%.1f", times)
  )

str(dat_heads)
summary(dat_heads$time_365.0)
summary(dat_heads$time_365.0)[c(1,6)]
# reticulate::py_help(object = flopy$modflow$mf$Modflow$load)
mf <- flopy$modflow$mf$Modflow$load(f = paths$mf_nam, 
                                    #model_ws = dirname(paths$mf_nam),
                                    load_only = "dis",
                                    verbose = TRUE)


# reticulate::py_help(object = flopy$utils$postprocessing$get_gradients)
gradients <- flopy$utils$postprocessing$get_gradients(
  heads = dat_heads$time_365.0,
  m = mf,
  nodata = c(-1e+30,1e+30))

summary(gradients)

```

[flopy.utils.postprocessing](https://flopy.readthedocs.io/en/latest/source/flopy.utils.postprocessing.html)


